import { config } from "dotenv";

config();

export const {
  DB_URL, DB_NAME, DB_PORT, DB_USER, DB_PASS, DB_HOST,
  NODE_ENV, PORT, LOG_FORMAT, ORIGIN, CREDENTIALS, JWT_SECRET,
  LOG_DIR, MAIL_HOST, MAIL_PORT, MAIL_USER, MAIL_PASS, GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET, GOOGLE_REDIRECT_URL, CLIENT_HOST
} = process.env;
