name: Run Tests
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev, main ]

jobs:

  container-job:
  
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres

        env:
          POSTGRES_PASSWORD: ${{ secrets.DB_PASS }}
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_DB: ${{ secrets.DB_NAME }}

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v3
      
      - name: Set up Node.js 17.x
        uses: actions/setup-node@v1
        with:
          node-version: 17.x

      - name: Install dependencies
        run: npm install

      - name: Run test
        run: npm test
        env:
          NODE_ENV: test
          TEST_DB_URL: ${{ secrets.DB_URL }}
          TEST_PORT: ${{ secrets.PORT }}
          LOG_DIR: ${{ secrets.LOG_DIR }}